{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1644bae7",
   "metadata": {},
   "source": [
    "# Predictions on Different Data <a name = 'beginning'></a>\n",
    "\n",
    "In this notebook I will experiment with data in order to get more accurate predictions of the models defined in FittingAndEvaluation notebook.   \n",
    "\n",
    "The test data was taken from the Kaggle competition, so there is no direct access to house sale prices. Therefore, the competition submissions will be used to evaluate all attempts. Each attempt will be accompanied by a screenshot of the result. \n",
    "\n",
    "### Steps  \n",
    "  \n",
    "- [Scoring Method](#scoring)   \n",
    "- [Data Loading](#loading)     \n",
    "- [Prediction on test data processed in EDA notebook](#processed_EDA)   \n",
    "- [Prediction on test data with different number of features](#diff_num)\n",
    "- [Prediction on normalized test data](#norm_data)     \n",
    "- [Prediction on scaled test data](#scaled)  \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "593baf06",
   "metadata": {},
   "outputs": [],
   "source": [
    "%store -r models\n",
    "%store -r models_results\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.preprocessing import StandardScaler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "ede1a023",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[LinearRegression(),\n",
       " Ridge(alpha=2.5384615384615383, random_state=0),\n",
       " Lasso(alpha=41, random_state=0),\n",
       " DecisionTreeRegressor(max_depth=6, max_features=37, min_impurity_decrease=0,\n",
       "                       min_samples_leaf=8, random_state=0),\n",
       " RandomForestRegressor(max_depth=27, max_features=12, min_samples_split=3,\n",
       "                       n_estimators=1150, n_jobs=-1, random_state=0),\n",
       " XGBRegressor(base_score=None, booster=None, callbacks=None,\n",
       "              colsample_bylevel=None, colsample_bynode=None, colsample_bytree=1,\n",
       "              device=None, early_stopping_rounds=None, enable_categorical=False,\n",
       "              eval_metric=None, feature_types=None, gamma=0, grow_policy=None,\n",
       "              importance_type=None, interaction_constraints=None,\n",
       "              learning_rate=0.25, max_bin=None, max_cat_threshold=None,\n",
       "              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,\n",
       "              max_leaves=None, min_child_weight=6, missing=nan,\n",
       "              monotone_constraints=None, multi_strategy=None, n_estimators=17,\n",
       "              n_jobs=None, num_parallel_tree=None, random_state=0, ...)]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "models"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5fb5f51",
   "metadata": {},
   "source": [
    "Since the elastic net equals Lasso regression, let's exclude it from the list of models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d7eda775",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[LinearRegression(),\n",
       " Ridge(alpha=2.5384615384615383, random_state=0),\n",
       " Lasso(alpha=41, random_state=0),\n",
       " RandomForestRegressor(max_depth=27, max_features=12, min_samples_split=3,\n",
       "                       n_estimators=1150, n_jobs=-1, random_state=0),\n",
       " XGBRegressor(base_score=None, booster=None, callbacks=None,\n",
       "              colsample_bylevel=None, colsample_bynode=None, colsample_bytree=1,\n",
       "              device=None, early_stopping_rounds=None, enable_categorical=False,\n",
       "              eval_metric=None, feature_types=None, gamma=0, grow_policy=None,\n",
       "              importance_type=None, interaction_constraints=None,\n",
       "              learning_rate=0.25, max_bin=None, max_cat_threshold=None,\n",
       "              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,\n",
       "              max_leaves=None, min_child_weight=6, missing=nan,\n",
       "              monotone_constraints=None, multi_strategy=None, n_estimators=17,\n",
       "              n_jobs=None, num_parallel_tree=None, random_state=0, ...)]"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "models.pop(3)\n",
    "models"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1cda55cb",
   "metadata": {},
   "source": [
    "# Scoring Method <a name = 'scoring'></a>  \n",
    "\n",
    "[Table of Content](#beginning)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "8a8af849",
   "metadata": {},
   "outputs": [],
   "source": [
    "# My metric for cross validation\n",
    "def rmse_log(model, X, y):\n",
    "    y_pred = model.predict(X)\n",
    "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e6ca558a",
   "metadata": {},
   "source": [
    "# Data Loading <a name = 'loading'></a>  \n",
    "\n",
    "[Table of Content](#beginning)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "5f7dee7a",
   "metadata": {},
   "outputs": [],
   "source": [
    "train_data = pd.read_csv('../../Data/train_data_processed.csv', index_col = 'Id')\n",
    "X = train_data.copy()\n",
    "y = X['SalePrice']\n",
    "X = X.drop(['SalePrice'], axis = 1)\n",
    "\n",
    "test_data = pd.read_csv('../../Data/test_data_processed.csv', index_col = 'Id')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1faa453a",
   "metadata": {},
   "source": [
    "# Prediction on test data processed in EDA notebook  <a name = 'processed_EDA'></a>  \n",
    "\n",
    "[Table of Content](#beginning)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "14ff686c",
   "metadata": {},
   "source": [
    "Let this be the starting point. Real predictions on real test data using models trained on data processed in an EDA notebook."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "8888a053",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get predictions of my best models on test data processed in EDA notebook\n",
    "for model in models:\n",
    "     \n",
    "    # fit / predict\n",
    "    model.fit(X, y)\n",
    "    prediction = model.predict(test_data)\n",
    "    \n",
    "    # Get submission name\n",
    "    cut_model_name_after = str(model).find('(')\n",
    "    model_name = str(model)[:cut_model_name_after]\n",
    "    submission_name = model_name + '_processed_EDA.csv'\n",
    "    \n",
    "    # Fit prediction to the submission format and save .csv\n",
    "    submission_dataframe = pd.DataFrame({'Id': test_data.index, 'SalePrice': prediction})\n",
    "    submission_dataframe.to_csv(f\"Submissions/{submission_name}\", index = False)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f462ec4a",
   "metadata": {},
   "source": [
    "![EDA](pics/EDA_result.png)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0ba2d848",
   "metadata": {},
   "source": [
    "Lasso regression gives the best results so far."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bd01045b",
   "metadata": {},
   "source": [
    "# Prediction on test data with different number of features <a name = 'diff_num'></a>\n",
    "\n",
    "[Table of Content](#beginning)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4430e2e6",
   "metadata": {},
   "source": [
    "Here I will try to fit my model to a different number of features that I selected using mutual information in the EDA notebook."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "52f35dc9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get a list of columns\n",
    "columns_list = list(X.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "ba5a508d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0  -  OverallQual\n",
      "1  -  GrLivArea\n",
      "2  -  YearBuilt\n",
      "3  -  GarageArea\n",
      "4  -  TotalBsmtSF\n",
      "5  -  FullBath\n",
      "6  -  YearRemodAdd\n",
      "7  -  2ndFlrSF\n",
      "8  -  LotArea\n",
      "9  -  Fireplaces\n",
      "10  -  OpenPorchSF\n",
      "11  -  Neighborhood_Blmngtn\n",
      "12  -  Neighborhood_Blueste\n",
      "13  -  Neighborhood_BrDale\n",
      "14  -  Neighborhood_BrkSide\n",
      "15  -  Neighborhood_ClearCr\n",
      "16  -  Neighborhood_CollgCr\n",
      "17  -  Neighborhood_Crawfor\n",
      "18  -  Neighborhood_Edwards\n",
      "19  -  Neighborhood_Gilbert\n",
      "20  -  Neighborhood_IDOTRR\n",
      "21  -  Neighborhood_MeadowV\n",
      "22  -  Neighborhood_Mitchel\n",
      "23  -  Neighborhood_NAmes\n",
      "24  -  Neighborhood_NPkVill\n",
      "25  -  Neighborhood_NWAmes\n",
      "26  -  Neighborhood_NoRidge\n",
      "27  -  Neighborhood_NridgHt\n",
      "28  -  Neighborhood_OldTown\n",
      "29  -  Neighborhood_SWISU\n",
      "30  -  Neighborhood_Sawyer\n",
      "31  -  Neighborhood_SawyerW\n",
      "32  -  Neighborhood_Somerst\n",
      "33  -  Neighborhood_StoneBr\n",
      "34  -  Neighborhood_Timber\n",
      "35  -  Neighborhood_Veenker\n",
      "36  -  Foundation_BrkTil\n",
      "37  -  Foundation_CBlock\n",
      "38  -  Foundation_PConc\n",
      "39  -  Foundation_Stone\n",
      "40  -  Foundation_Wood\n",
      "41  -  Exterior2nd_AsbShng\n",
      "42  -  Exterior2nd_AsphShn\n",
      "43  -  Exterior2nd_Brk Cmn\n",
      "44  -  Exterior2nd_BrkFace\n",
      "45  -  Exterior2nd_CmentBd\n",
      "46  -  Exterior2nd_HdBoard\n",
      "47  -  Exterior2nd_ImStucc\n",
      "48  -  Exterior2nd_MetalSd\n",
      "49  -  Exterior2nd_Plywood\n",
      "50  -  Exterior2nd_Stone\n",
      "51  -  Exterior2nd_Stucco\n",
      "52  -  Exterior2nd_VinylSd\n",
      "53  -  Exterior2nd_Wd Sdng\n",
      "54  -  Exterior2nd_Wd Shng\n",
      "55  -  Exterior1st_AsbShng\n",
      "56  -  Exterior1st_BrkFace\n",
      "57  -  Exterior1st_CemntBd\n",
      "58  -  Exterior1st_HdBoard\n",
      "59  -  Exterior1st_ImStucc\n",
      "60  -  Exterior1st_MetalSd\n",
      "61  -  Exterior1st_Plywood\n",
      "62  -  Exterior1st_Stucco\n",
      "63  -  Exterior1st_VinylSd\n",
      "64  -  Exterior1st_Wd Sdng\n",
      "65  -  Exterior1st_WdShing\n"
     ]
    }
   ],
   "source": [
    "# Get a number for each feature\n",
    "for i in range(0, len(columns_list)):\n",
    "    print(i, ' - ', columns_list[i])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "9a70325f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a DataFrame where we will store the results of models` performance\n",
    "scores_diff_num_features = pd.DataFrame({'model': [], 'num_of_features': [], 'score': []})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "a3e5af86",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\samur\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 140, in __call__\n",
      "    score = scorer(estimator, *args, **routed_params.get(name).score)\n",
      "  File \"C:\\Users\\samur\\AppData\\Local\\Temp/ipykernel_3436/544649345.py\", line 4, in rmse_log\n",
      "    return np.sqrt(mean_squared_error(np.log1p(y), np.log1p(y_pred)))\n",
      "NameError: name 'mean_squared_error' is not defined\n",
      "\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# Try each of best models\n",
    "for model in models:\n",
    "    # On different number of features from 5 to 15 (considering One-Hot encoding)\n",
    "    for number_of_columns in [5, 6, 7, 8, 9, 10, 11, 36, 41, 55, 65]:\n",
    "        scores = cross_val_score(model, \n",
    "                                 X[columns_list[:number_of_columns]], \n",
    "                                 y, \n",
    "                                 cv = 5, \n",
    "                                 scoring = rmse_log)\n",
    "        \n",
    "        # Store the results\n",
    "        scores_diff_num_features.loc[len(scores_diff_num_features)] = str(model), number_of_columns - 1, scores.mean()\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3e3c9dd6",
   "metadata": {},
   "source": [
    "Let's print the best result for every model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "c4941f48",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "\"None of [Float64Index([nan, nan, nan, nan, nan], dtype='float64')] are in the [index]\"",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_3436/334990498.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mmin_score_rows\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mscores_diff_num_features\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mloc\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mscores_diff_num_features\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgroupby\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'model'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'score'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0midxmin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[0mmin_score_rows\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\u001b[0m in \u001b[0;36m__getitem__\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m    929\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    930\u001b[0m             \u001b[0mmaybe_callable\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcom\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mapply_if_callable\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 931\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_getitem_axis\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmaybe_callable\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0maxis\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    932\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    933\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_is_scalar_access\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkey\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mtuple\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\u001b[0m in \u001b[0;36m_getitem_axis\u001b[1;34m(self, key, axis)\u001b[0m\n\u001b[0;32m   1151\u001b[0m                     \u001b[1;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Cannot index with multidimensional key\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1152\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1153\u001b[1;33m                 \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_getitem_iterable\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0maxis\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1154\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1155\u001b[0m             \u001b[1;31m# nested tuple slicing\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\u001b[0m in \u001b[0;36m_getitem_iterable\u001b[1;34m(self, key, axis)\u001b[0m\n\u001b[0;32m   1091\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1092\u001b[0m         \u001b[1;31m# A collection of keys\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1093\u001b[1;33m         \u001b[0mkeyarr\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mindexer\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_get_listlike_indexer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1094\u001b[0m         return self.obj._reindex_with_indexers(\n\u001b[0;32m   1095\u001b[0m             \u001b[1;33m{\u001b[0m\u001b[0maxis\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;33m[\u001b[0m\u001b[0mkeyarr\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mindexer\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcopy\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mallow_dups\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\u001b[0m in \u001b[0;36m_get_listlike_indexer\u001b[1;34m(self, key, axis)\u001b[0m\n\u001b[0;32m   1312\u001b[0m             \u001b[0mkeyarr\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mindexer\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnew_indexer\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0max\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_reindex_non_unique\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkeyarr\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1313\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1314\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_validate_read_indexer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkeyarr\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mindexer\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1315\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1316\u001b[0m         if needs_i8_conversion(ax.dtype) or isinstance(\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\indexing.py\u001b[0m in \u001b[0;36m_validate_read_indexer\u001b[1;34m(self, key, indexer, axis)\u001b[0m\n\u001b[0;32m   1372\u001b[0m                 \u001b[1;32mif\u001b[0m \u001b[0muse_interval_msg\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1373\u001b[0m                     \u001b[0mkey\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1374\u001b[1;33m                 \u001b[1;32mraise\u001b[0m \u001b[0mKeyError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"None of [{key}] are in the [{axis_name}]\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1375\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1376\u001b[0m             \u001b[0mnot_found\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mensure_index\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mmissing_mask\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mnonzero\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0munique\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyError\u001b[0m: \"None of [Float64Index([nan, nan, nan, nan, nan], dtype='float64')] are in the [index]\""
     ]
    }
   ],
   "source": [
    "min_score_rows = scores_diff_num_features.loc[scores_diff_num_features.groupby('model')['score'].idxmin()]\n",
    "min_score_rows"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "56d4f08f",
   "metadata": {},
   "source": [
    "We found the optimal number of features to train the models. Let's make a prediction."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dbaf1367",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a list with best number of features for every model\n",
    "cut_list = [36, 55, 65, 41, 36, 36]\n",
    "\n",
    "\n",
    "for i in range(len(models)):\n",
    "    # Get next model and corresponding num of features from cut_list\n",
    "    model = models[i]\n",
    "    num_features = cut_list[i] \n",
    "    \n",
    "    # Shrinking the training data and fitting the model\n",
    "    X_short = X.copy()\n",
    "    X_short = X_short[columns_list[:num_features]]\n",
    "    model.fit(X_short, y)\n",
    "    \n",
    "    # Making prediction on cutted test data\n",
    "    prediction_short = model.predict(test_data[columns_list[:num_features]])\n",
    "    \n",
    "    # Get submission name\n",
    "    cut_model_name_after = str(model).find('(')\n",
    "    model_name = str(model)[:cut_model_name_after]\n",
    "    submission_name = model_name + '_shorted.csv'\n",
    "    \n",
    "    # Fit prediction to the submission format and save .csv\n",
    "    submission_dataframe = pd.DataFrame({'Id': test_data.index, 'SalePrice': prediction})\n",
    "    submission_dataframe.to_csv(f\"Submissions/{submission_name}\", index = False)\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c6810745",
   "metadata": {},
   "source": [
    "# Prediction on normalized test data <a name = 'norm_data'></a>\n",
    "\n",
    "[Table of Content](#beginning)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bbc59e0a",
   "metadata": {},
   "source": [
    "In the EDA notebook, we found that some features can be successfully normalized using the log function. Let's try linear models that have the greatest potential to benefit from normalized data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9fcace3a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load normalized data\n",
    "train_data_stats = pd.read_csv('../../Data/train_data_stats.csv', index_col = 'Id')\n",
    "test_data_stats = pd.read_csv('../../Data/test_data_stats.csv', index_col = 'Id')\n",
    "\n",
    "# Prepare training data\n",
    "X_stats = train_data_stats.copy()\n",
    "y_stats = X_stats['SalePrice']\n",
    "X_stats = X_stats.drop(['SalePrice'], axis = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7da87ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_stats.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f675e2d7",
   "metadata": {},
   "source": [
    "As mentioned only linear models will be applied."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c03e02a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "linear_models = models[:3]\n",
    "linear_models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "474c1677",
   "metadata": {},
   "outputs": [],
   "source": [
    "cut_list_norm = [36, 55, 65]\n",
    "\n",
    "for i in range(len(linear_models)):\n",
    "    # Get next model and corresponding num of features from cut_list_norm\n",
    "    model = linear_models[i]\n",
    "    num_features = cut_list_norm[i] \n",
    "    \n",
    "    # Shrink normalized train data and fit the model\n",
    "    X_norm = X_stats.copy()\n",
    "    X_norm = X_norm[columns_list[:num_features]]\n",
    "    model.fit(X_norm, y_stats)\n",
    "    \n",
    "    # The target value in the training data is also normalized, \n",
    "    # so it is necessary to take the exponent to get the correct prediction\n",
    "    prediction_norm = np.exp(model.predict(test_data_stats[columns_list[:num_features]]))\n",
    "    \n",
    "    # Get submission name\n",
    "    cut_model_name_after = str(model).find('(')\n",
    "    model_name = str(model)[:cut_model_name_after]\n",
    "    submission_name = model_name + '_norm.csv'\n",
    "    \n",
    "    # Fit prediction to the submission format and save .csv\n",
    "    submission_dataframe = pd.DataFrame({'Id': test_data.index, 'SalePrice': prediction_norm})\n",
    "    submission_dataframe.to_csv(f\"Submissions/{submission_name}\", index = False)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5f216b9d",
   "metadata": {},
   "source": [
    "# Prediction on scaled test data <a name = 'scaled'></a>  \n",
    "\n",
    "[Table of Content](#beginning)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5450ef8",
   "metadata": {},
   "source": [
    "The last option I'm going to try is data scaling. Feature scaling is a good thing. It improves model performance, prevents features from dominating, and increases the generalizability of the model. I expect good results."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "669ee03c",
   "metadata": {},
   "outputs": [],
   "source": [
    "scaler = StandardScaler()\n",
    "\n",
    "# Scale data\n",
    "X_train_scaled = scaler.fit_transform(X)\n",
    "test_data_scaled = scaler.transform(test_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e50bf832",
   "metadata": {},
   "outputs": [],
   "source": [
    "for i in range(len(models)):\n",
    "    model = models[i]\n",
    "    model.fit(X_train_scaled, y)\n",
    "    \n",
    "    prediction_scaled = model.predict(test_data_scaled)\n",
    "    \n",
    "    # Get submission name\n",
    "    cut_model_name_after = str(model).find('(')\n",
    "    model_name = str(model)[:cut_model_name_after]\n",
    "    submission_name = model_name + '_scaled.csv'\n",
    "    \n",
    "    # Fit prediction to the submission format and save .csv\n",
    "    submission_dataframe = pd.DataFrame({'Id': test_data.index, 'SalePrice': prediction_scaled})\n",
    "    submission_dataframe.to_csv(f\"Submissions/{submission_name}\", index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2dfc8569",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
